#!/bin/sh

PID=$(cat $LICHESS_PID_FILE)
P_NAME="lichess JVM"
JSTAT=$JAVA_HOME/bin/jstat

function graphically() {

#       echo ${JPS_RESULTS[@]}
       JSTAT_RESULTS=(`$JSTAT -gcutil $PID`)
#       echo ${JSTAT_RESULTS[@]} # sample -> S0 S1 E O P YGC YGCT FGC FGCT GCT 29.05 0.00 48.66 56.90 99.22 82 1.498 2 0.178 1.676

       echo "ygct.value ${JSTAT_RESULTS[18]/./}"
       echo "fgct.value ${JSTAT_RESULTS[20]/./}"
       echo "agct.value ${JSTAT_RESULTS[21]/./}"

}

function conf() {

       echo "graph_title jstat gc time(${P_NAME})"
       echo "graph_args --lower-limit 0"
       echo "graph_scale yes"
       echo "graph_vlabel gc time (msec)"
       echo "graph_category Java"
       echo "ygct.label young GC time"
       echo "fgct.label full GC time"
       echo "agct.label all GC time"
       echo "ygct.type DERIVE"
       echo "ygct.min 0"
       echo "fgct.type DERIVE"
       echo "fgct.min 0"
       echo "agct.type DERIVE"
       echo "agct.min 0"
}

if [ "$1" = "config" ]; then
        conf
    exit 0
fi

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

graphically


