#!/bin/sh

PID=$(cat $LICHESS_PID_FILE)
P_NAME="lichess JVM"
JSTAT=$JAVA_HOME/bin/jstat

function graphically() {

       JSTAT_RESULTS=(`$JSTAT -gcutil $PID`)
       echo "ygc.value ${JSTAT_RESULTS[17]}"
       echo "fgc.value ${JSTAT_RESULTS[19]}"

}

function conf() {

       echo "graph_title jstat gc count(${P_NAME})"
       echo "graph_args --lower-limit 0"
       echo "graph_scale no"
       echo "graph_vlabel gc count"
       echo "graph_category Java"
       echo "ygc.label young GC count"
       echo "fgc.label full GC count"
       echo "ygc.type DERIVE"
       echo "ygc.min 0"
       echo "fgc.type DERIVE"
       echo "fgc.min 0"
}

if [ "$1" = "config" ]; then
    conf
    exit 0
fi

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

graphically 


