#!/bin/sh

PID=$(cat $LICHESS_PID_FILE)
P_NAME="lichess JVM"
JSTAT=$JAVA_HOME/bin/jstat

function graphically() {

       JSTAT_RESULTS=(`$JSTAT -gcutil $PID`)
#       echo ${JSTAT_RESULTS[@]} # sample -> S0 S1 E O P YGC YGCT FGC FGCT GCT 29.05 0.00 48.66 56.90 99.22 82 1.498 2 0.178 1.676

       echo "used_s0.value ${JSTAT_RESULTS[11]}"
       echo "used_s1.value ${JSTAT_RESULTS[12]}"
       echo "used_e.value ${JSTAT_RESULTS[13]}"
       echo "used_p.value ${JSTAT_RESULTS[15]}"
       echo "used_o.value ${JSTAT_RESULTS[14]}"

}

function conf() {

       echo "graph_title jstat gcutil(${P_NAME})"
       echo "graph_args -r --lower-limit 0"
       echo "graph_scale no"
       echo "graph_vlabel used %"
       echo "graph_category Java"
       echo "used_s0.label used Survivor0 %"
       echo "used_s1.label used Survivor1 %"
       echo "used_e.label used Eden %"
       echo "used_p.label used Metaspace %"
       echo "used_o.label used Old %"
}

if [ "$1" = "config" ]; then
    conf
    exit 0
fi

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

graphically ${item[@]}

