#!/bin/sh

PID=$(cat $LICHESS_PID_FILE)
P_NAME="lichess JVM"
JSTAT=$JAVA_HOME/bin/jstat

function graphically() {
       JSTAT_RESULTS=(`$JSTAT -gccapacity $PID`)

       echo "ngc.value ${JSTAT_RESULTS[20]}"

       echo "ogc.value ${JSTAT_RESULTS[26]}"

       echo "mc.value ${JSTAT_RESULTS[31]}"
       
       echo "s0c.value ${JSTAT_RESULTS[21]}"
       echo "s1c.value ${JSTAT_RESULTS[22]}"
       
       echo "ec.value ${JSTAT_RESULTS[23]}"       
}

function conf() {

       echo "graph_title jstat gc capacity(${P_NAME})"
       echo "graph_args --base 1024 --lower-limit 0"
       echo "graph_scale yes"
       echo "graph_vlabel memory capacity (KB)"
       echo "graph_category Java"
       
       echo "ngc.label new generation current KB"
       echo "ogc.label old generation current KB"
       echo "mc.label metaspace generation current KB"
       echo "s0c.label survivor0 space current KB"
       echo "s1c.label survivor1 space current KB"
       echo "ec.label eden space current KB"
}

if [ "$1" = "config" ]; then
    conf
    exit 0
fi

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

graphically 


